package factory.factoryMethod;

/**
 * @author charank
 *
 */
public class Point {
	private double x,y;

	private Point(double x, double y) {
		super();
		this.x = x;
		this.y = y;
	}
	
	/*
	 * The below constructor is not allowed because you cannot ovveride by argument names in JAVA
	 * 
	 * public Point(double rho, double theta) {
			x = rho*Math.cos(theta);
			y = rho*Math.sin(theta);
		}
	 */
	
	/**
	 * @param x - cartesian co-ordinate x
	 * @param y	- cartesian co-ordinate y
	 * @return point generated by cartesian co-ordinates
	 */
	public static Point newCartesianPoint(double x,double y) {
		return new Point(x, y);
	}
	
	
	/**
	 * @param rho : polar co-ordinate
	 * @param theta : polar co-ordinate
	 * @return pint generated by polar co-ordinates
	 */
	public static Point newPolarPoint(double rho,double theta) {
		return new Point(rho*Math.cos(theta),rho*Math.sin(theta));
	}

	@Override
	public String toString() {
		return "Point [x=" + x + ", y=" + y + "]";
	}
	
	
}
